logging:
  config: classpath:log/logback-spring.xml
  file:
    path: ../logs
  level:
    root: info
  logback:
    rolling-policy:
      max-file-size: 100MB
      max-history: 10
      total-size-cap: 20GB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.126.10:3306/easy-spring-staging-demo-db?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20

