server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: mvc-simple-demo
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false


mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.ess.demo.mvc.simple.modules.*.model.*;
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

